services:
  nestjs-api:
    container_name: nestjs-api
    depends_on:
      - db-mysql
    build:
      context: ./backend
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - /backend/.env

  react-ui:
    container_name: react-ui
    depends_on:
      - nestjs-api
    build:
      context: ./frontend
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app
      - /app/node_modules
  db-mysql:
    container_name: db-mysql
    image: mysql:8
    restart: always
    env_file:
      - /backend/.env
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
